/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kaızen_uygulama;

import java.sql.Connection;
import java.util.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author MFİ
 */
public class Kaızen_Ekel extends javax.swing.JFrame {

    String P_SICIL = "", P_ID = "", P_ADI = "", P_SOYADI = "", P_ORG_ID = "", P_O_SEVİYE = "";
    static String kaızId = "";

    /**
     * Creates new form Kaızen_Ekel
     */
    public Kaızen_Ekel() {

    }

    public Kaızen_Ekel( String P_ID, String P_SICIL,String P_ADI, String P_SOYADI, String P_ORG_ID, String P_O_SEVİYE) {

        this.P_ID = P_ID;
        this.P_SICIL = P_SICIL;
        this.P_ADI = P_ADI;
        this.P_SOYADI = P_SOYADI;
        this.P_ORG_ID = P_ORG_ID;
        this.P_O_SEVİYE = P_O_SEVİYE;

        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        LABEL7 = new javax.swing.JLabel();
        LABEL8 = new javax.swing.JLabel();
        LABEL9 = new javax.swing.JLabel();
        LABEL10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        Anasayfa = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));

        LABEL7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LABEL7.setText("KAİZEN AD");

        LABEL8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LABEL8.setText("KAİZEN KONU");

        LABEL9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LABEL9.setText("KAİZEN AÇIKLAMA");

        LABEL10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LABEL10.setText("KAİZEN UYGULANACAK ORGANİZASYON ID");

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        jTextField2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jTextField3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("Kaizen Ekle");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LABEL8, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LABEL7, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LABEL9, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LABEL10, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(73, 73, 73))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LABEL10, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LABEL7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LABEL9, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LABEL8, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jMenu1.setText("Seçenekler");

        Anasayfa.setText("Anasayfa");
        Anasayfa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnasayfaActionPerformed(evt);
            }
        });
        jMenu1.add(Anasayfa);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AnasayfaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnasayfaActionPerformed
        System.out.println("p_ıd=" + P_ADI);
        Ana_Sayfa a = new Ana_Sayfa(P_ID, P_SICIL, P_ADI, P_SOYADI, P_ORG_ID, P_O_SEVİYE);
        setVisible(false);
        a.setVisible(true);
    }//GEN-LAST:event_AnasayfaActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Ana_Sayfa a=new Ana_Sayfa(P_ID, P_SICIL, P_ADI, P_SOYADI, P_ORG_ID, P_O_SEVİYE);
        String kaizemAdı = jTextField2.getText();
        String kaizemKonu = jTextArea2.getText();
        String kaizemOrgId = jTextField3.getText();
        String kaizemAçıklama = jTextArea1.getText();

         if (bosMuEkle(P_SICIL, kaizemAdı, kaizemKonu, kaizemOrgId, kaizemAçıklama) == false) {
        Kaızen_Insert(P_SICIL, kaizemAdı, kaizemKonu, kaizemOrgId, kaizemAçıklama);

        setVisible(false);
        a.setVisible(true);
         }
           else {
            JOptionPane.showMessageDialog(null, "lütfen bos bırakmayınız");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    public static void Kaızen_Insert(String P_SICIL, String K_ADI, String K_KONUSU, String K_ORG_ID, String K_Açıklama) {

        PreparedStatement ps;
        String baslangıc, sorguKaızen;
        Date d;
        SimpleDateFormat ft2;
        Connection con;
        
        //false ile doludur boş bırakılınca kayıt yapmıyor
       
            d = new Date();
            ft2 = new SimpleDateFormat("yyyy.MM.dd hh:mm:ss");
            System.out.println(ft2.format(d));
            String K_SON_HARK_ID = "1";
            baslangıc = "0001.01.01 00:00:00";
            //DAHA SONRA DÜZELTME YAPARKEN KOLAYLIK OLSUN DİYE BURADA TUUTUM BASLANGIÇÇ DEĞERİNİ

            con = Kaızen_Uygulama.getConnection_Kaizen_Db();
            sorguKaızen = "INSERT INTO  KAIZEN_KAIZEN_TBL (K_ADI, K_KONU, K_BASV_TARH, K_TAMAM_TARH,"
                    + " K_SON_HARK_TARH, K_SON_HARK_ID, K_ORG_ID, K_RED_TARH,K_AÇIKLAMA,K_P_SICIL) VALUES \r\n"
                    + "(?, ?, TO_TIMESTAMP(?, 'YYYY-MM-DD HH24:MI:SS'), \r\n"
                    + "TO_TIMESTAMP(?,'YYYY-MM-DD HH24:MI:SS'),\r\n"
                    + "TO_TIMESTAMP(?, 'YYYY-MM-DD HH24:MI:SS'),\r\n"
                    + "?, ?, TO_TIMESTAMP(?, 'YYYY-MM-DD HH24:MI:SS'),?,?)";

            try {
                ps = con.prepareStatement(sorguKaızen);
                System.out.println(K_ADI);
                ps.setString(1, K_ADI);
                System.out.println(K_KONUSU);
                ps.setString(2, K_KONUSU);
                System.out.println(ft2.format(d));
                ps.setString(3, ft2.format(d));
                System.out.println(baslangıc);
                ps.setString(4, baslangıc);
                System.out.println(ft2.format(d));
                ps.setString(5, ft2.format(d));
                System.out.println(K_SON_HARK_ID);
                ps.setString(6, K_SON_HARK_ID);
                System.out.println(K_ORG_ID);
                ps.setString(7, K_ORG_ID);
                System.out.println(baslangıc);
                ps.setString(8, baslangıc);
                System.out.println(K_Açıklama);
                ps.setString(9, K_Açıklama);
                System.out.println(P_SICIL);
                ps.setString(10, P_SICIL);

                ps.executeUpdate();
                System.out.println(".alıştısfasdasdas");
                JOptionPane.showMessageDialog(null, "kaizen tabosu oluşturuldu");

                kaızIdBul(K_ADI, K_KONUSU, K_Açıklama, K_ORG_ID,P_SICIL);

                kaızenIslemTablosu(P_SICIL);

            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage());
                // TODO: handle exception
            }

       

    }

    public static boolean bosMuEkle(String P_SICIL, String K_ADI, String K_KONUSU, String K_ORG_ID, String K_Açıklama) {
        Connection con;
        boolean dolu = true;
        if (!P_SICIL.equals("") && !K_ADI.equals("") && !K_KONUSU.equals("")&& !K_ORG_ID.equals("") && !K_Açıklama.equals("")) {
            dolu = false;
        }
        return dolu;
    }
    //Burada ıslem tablosuna gereken itemleri giriyorum
    //durum tablosuna 1 yanı oluşturuldu durumunu atıyorum

    public static void kaızenIslemTablosu(String I_Sıcıl) {
        String sorguIslem;
        PreparedStatement ps;
        Date d;
        SimpleDateFormat ft2;
        Connection con = Kaızen_Uygulama.getConnection_Kaizen_Db();

        d = new Date();
        ft2 = new SimpleDateFormat("yyyy.MM.dd hh:mm:ss");
        System.out.println(ft2.format(d));

        System.out.println("işlem tablosuna geliyor");
        System.out.println("bilgiler=" + kaızId + " " + I_Sıcıl + "");

        System.out.println("işlem tablosuna geliyor" + kaızId + " " + I_Sıcıl + " ft2.format(d)");
        sorguIslem = "INSERT INTO KAIZEN_ISLEM_TBL (I_SICIL_ID, I_KAIZ_ID, I_DURUM_ID, I_OPER_SAAT) VALUES "
                + "('" + I_Sıcıl + "', '" + kaızId + "', '1', TO_TIMESTAMP('" + ft2.format(d) + "', 'YYYY-MM-DD HH24:MI:SS'))";

        try {

            ps = con.prepareStatement(sorguIslem);

            ps.executeUpdate();

            JOptionPane.showMessageDialog(null, "işlem tablosu oluşturuldu");

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
            // TODO: handle exception
        }

    }
    //EĞER BAŞVURU TARİHİNİ DE EKLERSEM TAM ANLAMIYLA OLACAK

    public static void kaızIdBul(String K_ADI, String K_KONU, String K_Açıklama, String K_ORG_ID,String P_SICILARA) {
        Connection con;
        con = Kaızen_Uygulama.getConnection_Kaizen_Db();
        String sorguIdBulma;
        Statement st;
        ResultSet rs;
        SimpleDateFormat ft3;

        ft3 = new SimpleDateFormat("yyyy.MM.dd hh:mm:ss");

        //KAIZEN ADINI UNİQUE KOYDUM Kİ ID SINE ULAŞABİLMEK İÇİN
        sorguIdBulma = "SELECT * FROM KAIZEN_KAIZEN_TBL WHERE (K_ADI='" + K_ADI + "') AND (K_KONU='" + K_KONU + "') AND "
                + "(K_AÇIKLAMA='" + K_Açıklama + "') AND (K_ORG_ID='" + K_ORG_ID + "') AND (K_P_SICIL='" + P_SICILARA + "')";
        try {

            st = con.createStatement();
            rs = st.executeQuery(sorguIdBulma);

            while (rs.next()) {

                kaızId = rs.getString("K_ID");

            }
            System.out.println("kaizen ıd si=" + kaızId);
        } catch (Exception e) {
            // TODO: handle exception
        }

    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Kaızen_Ekel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Kaızen_Ekel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Kaızen_Ekel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Kaızen_Ekel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Kaızen_Ekel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Anasayfa;
    private javax.swing.JLabel LABEL10;
    private javax.swing.JLabel LABEL7;
    private javax.swing.JLabel LABEL8;
    private javax.swing.JLabel LABEL9;
    private javax.swing.JButton jButton1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
